[package]
name = "ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
livesplit-core = { version = "0.12.0", features = ["software-rendering"] }
eframe = "0.20.1"
livesplit-hotkey = "0.6.0"